name: Frontend Deploy
on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BUILD_INSTANCE_IP }}
          username: ${{ secrets.EC2_BUILD_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/test-ci-cd
            git reset --hard
            git pull
            cd ./frontend
            npm install
            npm run build
            scp -i ~/server.pem -r dist ${{ secrets.EC2_SERVE_SSH_USERNAME }}@${{ secrets.EC2_SERVE_INSTANCE_IP }}:~/test
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVE_INSTANCE_IP }}
          username: ${{ secrets.EC2_SERVE_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/test
            mkdir test2
            pm2 restart --name FE
