name: Deploy to EC2
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        working-directory: ./backend
        run: npm install
      - name: Build React frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-49-148-239.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/test-ci-cd
            git pull origin dev
            if git diff --quiet HEAD^ HEAD -- frontend/; then
              echo "No changes in frontend, skipping deployment"
            else
              cd ./frontend
              npm install
              npm run build
            fi
            if git diff --quiet HEAD^ HEAD -- backend/; then
              echo "No changes in backend, skipping deployment"
            else
              cd ../backend
              npm install
            fi
